import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import FlexpaLink from '@flexpa/link'
import { ThreeCircles, Hearts, MutatingDots, RotatingTriangles, ColorRing } from 'react-loader-spinner'
import { JsonViewer } from '@textea/json-viewer'
import { ocean } from '../styles/jsonViewer'
import { getAccessToken, getPatientId, getExplanationOfBenefit } from '../domain/utils'
import { useEffect, useState } from 'react'

export default function Home() {

  const [accessToken, setAccessToken] = useState("")
  const [patientId, setPatientId] = useState("")
  const [patientData, setPatientData] = useState({})
  const [pageError, setPageError] = useState(false)
  const [pageLoading, setPageLoading] = useState(false)

  useEffect(() => {
    // Run on client-side only
    FlexpaLink.create({
      // Replace with your publishable key
      publishableKey: process.env.NEXT_PUBLIC_PUBLISHABLE_KEY ?? '',
      onSuccess: (publicToken) => {
        // Send `publicToken` to your backend to exchange it for a patient `access_token`
        // https://www.flexpa.com/docs/sdk/login#exchange
        setPageLoading(true)
        getAccessToken(publicToken)
          .then(at => {
            at && setAccessToken(at)
            return at && getPatientId(at)
          })
          .then(id => id && setPatientId(id))
          .then(() => {
            setPageLoading(false)
            setPageError(false)
          })
          .catch(e => setPageError(true))
      }
    })
  }, [])

  const handleGetData = () => {
    setPatientData({})
    setPageLoading(true)
    setPageError(false)
    getExplanationOfBenefit(patientId, accessToken)
      .then(d => d && setPatientData(d))
      .then(() => {
        setPageLoading(false)
        setPageError(false)
      })
      .catch(e => setPageError(true))
  }

  const displayError = pageError ? (
    <p>Sorry, something went wrong</p>
  ) : (
    null
  )

  return (
    <div className={styles.container}>
      <Head>
        <title>Patient Data Downloader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Patient{' '}
          <span className={styles.secondaryTheme}>Data</span>{' '}
          Downloader
        </h1>

        <h1 className={styles.title}>
        ⚕️
        </h1>

        { pageLoading ? null : (
          <p className={styles.description}>
            To retrieve your data:
          </p>
        ) }

        <br />

        <div className={styles.column}>
          <div>
            { pageLoading ? (
              <ThreeCircles
                height="80"
                width="80"
                color="violet"
                ariaLabel="loading"
              />
            ) : !patientId ? (
              <button onClick={() => FlexpaLink.open()}>1. Link your health payer</button>
            ) : (
              <button onClick={handleGetData}>2. Download your data</button>
            ) }
          </div>
          <div className={styles.error}>
            { displayError }
          </div>
          <div>
            { Object.keys(patientData).length !== 0 ? (
              <JsonViewer value={patientData} theme={ocean}/>
            ) : (
              null
            ) }
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
